[tool.black]
include = ".pyi?$"
exclude = """
/(
    .git
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
)/
"""
line-length = 88
target-version = ["py310"]

[tool.isort]
include_trailing_comma = true
lines_after_imports = 2
multi_line_output = 3
profile = "black"
py_version = 310
